### PR TITLE
Venus withdrawal issue fixed

### PR DESCRIPTION
**Pull request by CryptJS13**
Withdrawals now only redeem how much is necessary. Withdrawal fee is taken by the withdrawer, not by whole vault. Folding disabled for all strategies.

Tested partial withdrawal and full withdrawals, everything functional.

### CODE REVIEW

**Comment by breadforthepeople** [comment]
Could base the withdrawal fix on the version that is currently in prod (not V2)? The diff is currently bigger and includes the changes in the PR https://github.com/harvest-finance/harvest-strategy-bsc/pull/21 that is not shipped.

**Comment by CryptJS13** [comment]
Partial withdrawal with the fold logic of the old version is very difficult. I can make it so it works with 0 folds, but it won't be functional when setting folds. That's what I fixed in V2.

**Comment by CryptJS13** [comment]
@breadforthepeople Working on it now, done in an hour.

**Comment by CryptJS13** [comment]
https://github.com/harvest-finance/harvest-strategy-bsc/pull/30

**Pull request closed without merging**
